import { AccountDetailsProps } from '@/screens/accountDetails/accountDetails';
import { ActionItemListProps } from '@/screens/actionItemList/actionItemList';
import { AddActionItemProps } from '@/screens/addActionItem/addActionItem';
import { AddScheduleActionItemProps } from '@/screens/addScheduleActionItem/addScheduleActionItem';
import { AddScheduleEventProps } from '@/screens/addScheduleEvent/addScheduleEvent';
import { AddScheduleMessageProps } from '@/screens/addScheduleMessage/addScheduleMessage';
import { AddSchedulePostProps } from '@/screens/addSchedulePost/addSchedulePost';
import { AddScheduleReminderProps } from '@/screens/addScheduleReminder/addScheduleReminder';
import { ChatProps } from '@/screens/chat/chat';
import { ChatImageUploadProps } from '@/screens/chat/chatImageUpload';
import { ChatGroupMemberProps } from '@/screens/chatGroupMember/chatGroupMember';
import { CommunityProps } from '@/screens/community/community';
import { ContactVaultProps } from '@/screens/contactVault/contactVault';
import { CreateLicenseCertificateProps } from '@/screens/createLicenseCertificate/createLicenseCertificate';
import { CreatePostProps } from '@/screens/CreatePost/CreatePost';
import { CustomNotificationProps } from '@/screens/customNotification/customNotification';
import { DashBoardProps } from '@/screens/dashboard/dashboard';
import { EventDetailScreenProps } from '@/screens/eventDetailScreen/eventDetailScreen';
import { FeedProps } from '@/screens/feed/feed';
import { GroupMembersProps } from '@/screens/groupMembers/groupMembers';
import { HtmlRenderScreenProps } from '@/screens/htmlRenderScreen/htmlRenderScreen';
import { MemberProfileProps } from '@/screens/memberProfile/memberProfile';
import { MyAccountsProps } from '@/screens/myAccounts/myAccounts';
import { NotificationProps } from '@/screens/notifications/notifications';
import { ProfileProps } from '@/screens/profile/profile';
import { ProfileEditProps } from '@/screens/profileEdit/profileEdit';
import { ResourceSubCategoryProp } from '@/screens/resourcesSubCategory/resourcesSubCategory';
import { ScheduleActionItemDetailProps } from '@/screens/scheduleActionItemDetail/scheduleActionItemDetail';
import { ScheduleDirectMessageDetailProps } from '@/screens/scheduleDirectMessageDetail/scheduleDirectMessageDetail';
import { ScheduledPostDetailProps } from '@/screens/scheduledPostDetail/scheduledPostDetail';
import { ScheduleEventDetailProps } from '@/screens/scheduleEventDetail/scheduleEventDetail';
import { ScheduleGroupMessageDetailProps } from '@/screens/scheduleGroupMessageDetail/scheduleGroupMessageDetail';
import { ScheduleReminderDetailProps } from '@/screens/scheduleReminderDetail/scheduleReminderDetail';
import { SupportProps } from '@/screens/support/support';
import { UploadSecureFilesProps } from '@/screens/uploadSecureFiles/uploadSecureFiles';
import { VaultProps } from '@/screens/vault/vault';
import { SubNavigator } from '@/utils/navigationUtils';
import { DrawerStackParamList } from '../drawerStackParamList/drawerStackParamList';

export type RootStackParamList = {
  Splash: undefined;
  Login: undefined;
  MyReferrals: undefined;
  MyTeams: undefined;
  ReferFriend: undefined;
  ActionItemList?: ActionItemListProps | undefined;
  DrawerRoutes: SubNavigator<DrawerStackParamList>; // Drawer Stack
  ContactUs: undefined;
  AddScheduleEvent?: AddScheduleEventProps | undefined;
  AddSchedulePost?: AddSchedulePostProps | undefined;
  AddScheduleReminder: AddScheduleReminderProps | undefined;
  SettingSetup: undefined;
  TimeZone: undefined;
  GroupMembers: GroupMembersProps | undefined;
  MemberProfile: MemberProfileProps | undefined;
  Agreement: undefined;
  Faq: undefined;
  Support: SupportProps | undefined;
  HelpCenter: undefined;
  Chat: ChatProps | undefined;
  HtmlRenderScreen: HtmlRenderScreenProps | undefined;
  TypographyScreen: undefined;
  EventDetailScreen: EventDetailScreenProps | undefined;
  ResourceSubCategory: ResourceSubCategoryProp | undefined;
  ChatGroupMember: ChatGroupMemberProps | undefined;
  EventViewAll?: undefined;
  Profile?: ProfileProps | undefined;
  ProfileEdit?: ProfileEditProps | undefined;
  CreatePost?: CreatePostProps | undefined;
  Community: CommunityProps | undefined;
  Vault?: VaultProps | undefined;
  AddActionItem?: AddActionItemProps | undefined;
  AddScheduleMessage?: AddScheduleMessageProps | undefined;
  AddScheduleActionItem?: AddScheduleActionItemProps | undefined;
  Notifications?: NotificationProps | undefined;
  ContactFeed: FeedProps | undefined;
  Dashboard: DashBoardProps | undefined;
  CustomNotification: CustomNotificationProps | undefined;
  ContactVault: ContactVaultProps | undefined;
  UploadSecureFiles: UploadSecureFilesProps | undefined;
  SettingsScreen: undefined;
  SessionOutScreen: undefined;
  ChatImageUpload: ChatImageUploadProps | undefined;
  CreateLicenseCertificate: CreateLicenseCertificateProps | undefined;
  PasswordSetup: undefined;

  ScheduledPostDetail: ScheduledPostDetailProps | undefined;
  ScheduleEventDetail: ScheduleEventDetailProps | undefined;
  ScheduleReminderDetail: ScheduleReminderDetailProps | undefined;
  ScheduleActionItemDetail: ScheduleActionItemDetailProps | undefined;
  ScheduleDirectMessageDetail: ScheduleDirectMessageDetailProps | undefined;
  ScheduleGroupMessageDetail: ScheduleGroupMessageDetailProps | undefined;
  MyAccounts: MyAccountsProps;
  AccountDetails: AccountDetailsProps;
};
