export type SignalRMessageModel = {
  userName?: string;
  userId?: number;
  tenantId?: number;
  targetUserId?: number;
  targetTenantId?: string;
  side?: number;
  readState?: number;
  receiverReadState?: number;
  message?: string;
  messageType?: string;
  imageURL?: string;
  link?: null | string;
  imageB64?: null | string;
  creationTime?: string;
  creationTimeStr?: string;
  sharedMessageId?: string;
  profileImageID?: string;
  profileImage?: string;
  initials?: string;
  creationTimeAgo?: string;
  metaData?: string;
  phoneIdentifier?: string;
  placeOfTrigger?: null | string;
  groupId?: null | string;
  fullName?: string;
  colorCode?: string;
  id?: number | string;
  fileName?: string;
  contentType?: string;
  linksSend?: boolean;
  fullImagePath?: string;
  isImageLoading?: boolean;
  imageOrFileId?: string;
  sendFailed?: boolean;
  showProfile?: boolean;
  imageS3Url?: string;
  isPdfOpening?: boolean;
  status?: string;
  marginTop?: number;
  animate?: boolean;
  creationTimeDisplay?: string;
  emailAddress?: string;
};
