export type GetUserForChatModel = {
  serverTime?: string;
  utcTime?: string;
  friends?: any[];
  userChatList?: UserChatList[];
};

// export type UserChatList = {
//   friendUserId?: number;
//   friendTenantId?: number;
//   friendUserName?: string;
//   friendTenancyName?: string;
//   friendProfilePictureId?: any;
//   friendProfilePicture?: string;
//   unreadMessageCount?: number;
//   isOnline?: boolean;
//   isProgramOneOnOne?: boolean;
//   state?: number;
//   userFullName?: string;
//   programID?: any;
//   sessionID?: any;
//   programName?: string;
//   programTypeID?: number;
//   sessionName?: string;
//   activeInProgram?: boolean;
//   lastSendMsg?: string;
//   lastSendMsgDTAgo?: any;
//   lastSendMsgDT?: any;
//   lastMessageType?: any;
//   lastSendMsgCreate?: any;
//   roleName?: any;
//   initials?: string;
//   groupId?: any;
//   emailAddress?: string;
//   userId?: number;
//   adminId?: any;
//   groupMemberCount?: string;
//   groupName?: any;
//   groupProfilePicture?: any;
//   key?: string;
//   isSelected?: boolean;
//   isAdmin?: boolean;
// };

export type UserChatList = {
  friendUserId?: number;
  targetUserId?: number;
  friendTenantId?: any;
  targetTenantId?: number;
  friendUserName?: any;
  targetUserName?: string;
  friendTenancyName?: any;
  targetTenancyName?: string;
  friendProfilePictureId?: any;
  targetProfilePictureId?: string;
  friendProfilePicture?: any;
  targetProfilePicture?: string;
  unreadMessageCount?: number;
  isOnline?: boolean;
  isProgramOneOnOne?: boolean;
  state?: number;
  userFullName?: string;
  programID?: any;
  sessionID?: any;
  programName?: string;
  programTypeID?: number;
  sessionName?: string;
  activeInProgram?: boolean;
  lastSendMsg?: string;
  lastSendMsgDTAgo?: any;
  lastSendMsgDT?: any;
  lastMessageType?: any;
  lastSendMsgCreate?: any;
  roleName?: any;
  initials?: string;
  groupId?: string | null;
  emailAddress?: string;
  userId?: number;
  adminId?: any;
  isGroupAdmin?: boolean;
  groupMemberCount?: string;
  groupName?: any;
  groupProfilePicture?: any;
  isInactive?: boolean;
  contactKey?: string;
  isSelected?: boolean;
  groupInactive?: boolean;
  groupInactiveMessage?: string;
  inactiveMessage?: string;
  teamHeaderId?: string;
  groupUserId?: number;
  status?: string;
  statusClass?: string;
  isOutOfOffice?: boolean;
  endDate?: string;
  isSystemCreatedGroup?:boolean;
};
